### ISSUE TITLE
Signal 'ScrollReleased' is missing

### ISSUE THREAD

**Issue by Caviarbro** [EmeraldSlash/RbxMouse#8]
As title says there is currently no ScrollReleased signal (Enum.UserInputType.MouseWheel).

**Comment by EmeraldSlash** [comment]
The action of scrolling the mouse wheel does not fire Begin/End signals. It only fires Changed. If you would specifically find Begin/End signals for mouse wheel scrolling useful I'd consider adding them to the library. However what gets put in the library would probably be pretty arbitrary and dependent on the use case which makes me reluctant.

If you're meaning the mouse button, not the actual wheel scrolling, that is covered by RbxMouse.Button3Released (and other 'Button3' signals).

**Comment by Caviarbro** [comment]
Yeah I've actually meant the Scrolling after some time I have found myself that there's not really InputEnded for it. I am using my custom solution that's using os.clock() and task.wait() but I would still much appreciate this to be built in so I don't need to have functions regarding mouse outside of RbxMouse.

**Comment by EmeraldSlash** [comment]
Can you send your code so that I can see exactly what you're looking for?

Like I said before, I am reluctant to do this since the meaning of "begin" and "end" of scrolling input could change a lot depending on the use case (meaning people who use this library may find this feature useless to solve their problem).

Having code outside of RbxMouse isn't bad per se - the goal of RbxMouse is to solve common problems with the mouse that everyone has. If the problem you are solving isn't present or is in a different for form other people then there's not much point putting your solution in a library since they won't be able to use it.

But anyway, if your code does seem genuinely useful across different use-cases, then I'll add it.

**Comment by Caviarbro** [comment]
I can't really say if it can be useful across "different" use case but I've came up with something this:
```lua
local RbxMouse = require(...)
local lastInput 
local isScrolling 
local waitTime = 0.25

local function ScrollRelease(savedInput)
       task.wait(waitTime)
       isScrolling = savedInput ~= lastInput
end

RbxMouse.Scrolled:Connect(function(direction,inputObject)
isScrolling = true
lastInput = inputObject
ScrollRelease(inputObject)
end)
```

**Comment by EmeraldSlash** [comment]
`savedInput ~= lastInput` will always be false since the InputObject never changes. It would probably be better to use a timestamp like `os.clock()` or an incrementing number to uniquely identify each scroll.

But also what is the actual code you used in your project?

**Comment by Caviarbro** [comment]
Thanks for the information.
I am using it to show Informations of Items that you hover over with mouse, inside scrolling frame.
Game that does the exact thing is: Pet Simulator X. (Open inventory and hover your mouse over the pet, for UX reasons I've decided to implement something like this because when you are scrolling through the inventory the flickering description is not really great to look at + I didn't want to use any AbsoluteCanvasPosition change signal and wanted to make it only from inputs.)

**Comment by EmeraldSlash** [comment]
Ah you don't need the scrolling signals for that. It would be unreliable- for example if the window size changes or the frame or item moves (without scrolling) then the hover popup won't update. ScrollingFrames also scroll smoothly, so inputs (which are not smooth) won't accurately detect when the movement happens.

Instead, you should listen to the AbsolutePosition property change signal on the item (and possibly the AbsoluteSize signal as well) . Or you can just update the hover label every frame inside RenderStepped without having to think about signals.
